###服务端口号
server:
  port: 8200
###服务别名---服务注册到注册中心名称
spring:
  application:
    name: eureka
###eureka基本信息配置
eureka:
  instance:
    ###注册中心ip地址
    hostname: localhost
  client:
    serviceUrl:
      ##注册地址
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    ####因为自己是注册中心，是否需要将自己注册给自己的注册中心（集群的时候是需要为true）
    register-with-eureka: true
    ###因为自己是注册中心，不需要去检索服务信息
    fetch-registry: true
